### ISSUE TITLE
Ask for the dataset information

### ISSUE THREAD

**Issue by 233papertiger** [Sup31/PandorasBooks#1]
Hello, I am looking for the dataset PANDORA. Does this dataset come from the paper **PANDORA Talks: Personality and Demographics on Reddit**? I have submitted my application for the dataset, but have not received a response. May I ask if it is convenient to provide this dataset!

**Comment by Sup31** [comment]
Hi Xiao,
It took them 4 days to get back to me. They are pretty prompt. I am not
supposed to share the dataset. This was the email address I got the dataset
from -
Matej.Gjurkovic@fer.hr
You could probably try emailing him.
Best,
Supriya Paulose

**Comment by 233papertiger** [comment]
Fine, thanks. You've been a big help.

**Comment by Sup31** [comment]
The academic community has rules about sharing of datasets that have
personal information. Keep your attitude under check. It is not needed
here.
